spring.datasource.url=jdbc:h2:file:/app/data/weight-loss-tracker-v2;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;DEFAULT_NULL_ORDERING=HIGH
spring.h2.console.enabled=false

app.cors.allowed-origins=http://localhost:8080,http://127.0.0.1:8080
app.spa.enabled=true
